const Colors = {
  Gold: "\x1b[38;5;220m",
  Red: "\x1b[31m",
  Teal: "\x1b[38;5;51m",
  Green: "\x1b[32m",
  Neon: "\x1b[38;5;198m",
  Blue: "\x1b[34m",
  Magenta: "\x1b[95m",
  Dim: "\x1b[2m",
  RESET: "\x1b[0m"
};

const banner = `
                             .l;                                                                                                                                                                                                                    .o,                                                     
                             .x0c.                                                                                                                                                                                                                 ,k0;                                                     
.:.                           cNWOc.                                                                                                                                                                                                            .;xNWx.                           ;,                        
'OKl.        .::              .lXMWKd,.                                                                                                    ..                                                                                                 'lONMWk.              'l'        .;kKc                        
 lNWXd;.      lXOc.             ;0WMMN0o;.                                                                                                ;Oo                                                                                              'ckNMMMXo.            .;xXk.      'l0WWk.                        
 .oNMMWKd:.   .dWWKx:.           .cOWMMMWKdc.                                                                                         .'ckNM0,                                                                                         .;oONMMMWXd,           .,o0NM0,   .,oONMMWk.                         
   ;OWMMMWXkl;..lXMMWXkl;.       .;ox0NMMMMWXOo:.                                                                              .,:lodk0NWMMMWd                                                                                     .;lkKWMMMMWKkdc.       .'cx0WMMNx,.,cx0WMMMMXl.                          
    .c0WMMMMMWXkdkXMMMMMWKko:'.   .o0XNWMMMMMMMWXOdc'.                                                                    ,oodOXWMMMMMMMMMMM0'                                                                                ..;okKWMMMMMMMMWXKx,    .;lx0NMMMMMWOdxKNMMMMMWXd'                            
      .:xXWMMMMMMMWMMMMMMMMMMN0ko:,.,o0WMMMMMMMMMMMMNKko;'.                                                             .:0WMMMMWKxlkWMMMMMMXk:.                                                                          .;lx0XWMMMMMMMMMMMWXx;.';lxOXWMMMMMMMMMWWMMMMMMMNOl.                              
       ':ldkKWMMMMMMMMMMMMMMMMMMMMWXOxkXMMMMMMMMMMMMMMMMWN0xo:'.   .;;.                                              .oOXWMMMMMXkc:dXMMMMMMMMMNc                                                              ':'   ..;lxOXWMMMMMMMMMMMMMMMMNOxkKNWMMMMMMMMMMMMMMMMMMMWXOxlc,.                              
       .:k00KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOdl:lkOd:'.                                         ,0MMMMMMMMMWWWWMMMMMMMMMMMMKl.                                                        .;okOo:cok0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK00Ol.                               
          ,xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXWMWN0xo:,..                                   ;XMXdc:clkNMMWMMMMMMMMMMMMMMXl.                                                ..';ldOXWMWNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc.                                 
            .cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0Oxdooollc:;,'..                    cKx.   .xNMMMMMMMMMMMMMMMMMMXc                                 ..,;:cclooodxkOKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'                                    
            'ccoxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxl;.                .'. .,cddlxXMMMMMMMMMMMMMMMWKc.                         .,cdk0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxocl,                                    
             :0WNXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk:.                       .kMMMMMMMMMMMMMMMMWXl.                      ,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNWKo.                                    
              .cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.                     cXMMMMMMMMMMMMMMMMMMXl'.                  ,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'                                      
                .,oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.                  .cKMMMMMMMMMMMMMMMMMMMKx:                ,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.                                        
                  ':lxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o'                .xWMMMMMMMMMMMMMMMMMMMNXk,            .ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0koc;.                                         
                  ,d0XKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl,.            ,KMMMMMMMMMMMMMMMMMMMMMMWk.        .cxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKXKx;.                                         
                    .ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o;.         ;KWMMMMMMMMMMMMMMMMMMMMMMXo.    'lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMNOo,                                            
                       .:ok0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o,       :0WMMMMMMMMMMMMMMMMMMMMMMNx,..ckXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOdc'.                                              
                       'looxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNKxdooodx0XNNNNNNNNNNNNNNNNNNNNNNNNN0k0NNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxdoo;.                                              
                        'ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOcoxxxxxxxxxxxxxxxxxxxxxxc'''''''''''''''''''''''''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo;.                                               
                           .:ok0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd:KMMMMMMMMMMMMMMMMMMMMMWo                         :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOdc'.                                                  
                          .;cclx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo:KNO0MMMMMMMMMMMMNOKMMMWd         .';;;,'..       ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkocc:.                                                  
                           ,lkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo:KO':NMMMMMMMMMMMx.oWMMWo      'lkKNWMMWNX0xl'    ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;.                                                  
                              .,cok0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo:0c lWMMMMMMMMMMMO..OMMWo    .dXMMMMMMMMMMMMMXd'  ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdl;'.                                                     
                              .cxkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo:O; 'dkxlcc:cldkx:..xMMWo    oWMMMMMMMMMMMMMMMMd. ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0Okl,                                                      
                                'cxKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo:K0l'            .:kNMMWo   .oOxodx0WMMMMNO0K00l  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko;.                                                       
                                   .;cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo:KMWKo:.       .;o0KKKKKl    ..    .dXWMMk......  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:.                                                           
                                    .:d0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo:KMMMMWk.     ,lkK000000kxkkkkkkx; 'kWWMMO'       ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkl,                                                            
                                      .;cdk0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo:KMMMMMX:    .lxKMMMMMM0:xWMMMMMWo.,cccccc,.      ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Oxl:'                                                              
                                           .,d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd:KMMMMMNd;,,,lxxKMMMMMX: .OMMMMMWo                :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk:.                                                                   
                                             .,cdkO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,oOOOkkkkkkkkOoo00l:::,   .:::cxXo................cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Okdl;'                                                                     
                                                 .;okKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.   .          ,KN0o;       'lkXNxxXNNXXNNXXNNXN0:lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOd:.                                                                         
                                                  .,:ldkO00KXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'  .lc'.  ,c,  'OMMMO'     .dWMMXxOMMMWKkdoooxONK:dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKK0Okxoc;'.                                                                         
                                                        .;lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX; .;ldx:..oNX; .dWMXc.;okx:.,OMM0xKXkdl,';lo:''kk;kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKko:.                                                                                
                                                        .,lx0XNNWWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo  ;c,;d: .xW0; 'OWXk0WMMMWXk0WXxkx;'':d0NMMO,'dl:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNWWWNX0kd:.                                                                                
                                                             ..';cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'  ;l;cx:..lKXd'.oXWMMMMMMMMN0xo:.,x0XMMMMNo.;d:dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xo;''..                                                                                    
                                                                 ,loddxxddONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd. .ld::do'.;d00o;,ckKWMWX0Okxo,'lKMMMMMMXd,,occXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxddxxdol:.                                                                                        
                                                                         'oxxxxdoONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. .:llccoc. 'xK0o,..,lk00XKo',xNMMMMMMKl':xccKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dodxkxd;.                                                                                                
                                                                              .:xKNNNX0kxKWMMMMMMMMMMMMWWMMMMMMMMMMNd.  ;xko;co:'..lNNO, ,0MWWx,,xWMMMMMXk;'lxclKMMMMMMMMMMWWWMMMMMMMMMMMMXkx0KXNNXOl.                                                                                                      
                                                                              ..''''.',lONMWXO0NMMMMW0xONMMMMMMMMMMMWO;  .;cc::ll:c,';:;.,0MWNo.;0MWXOxd;'cdocxNMMMMMMMMMMMWKxONMMMMWKOKNWWKo;'.'''''.                                                                                                      
                                                                                     .:llc:;cdKWNKkoclONMWX0XMMMMMMMMMNx,   ,oooc:l;     ,KMMWk;':o:;,.;odocoKWMMMMMMMMN0KWMW0dllx0XWNkl::cloc'                                                                                                             
                                                                                           'clc;'..;dOOkdc,cKMMMMMMMMMMMNk:.  .:c.       ,KMMMWXkoodkOkxoldKMMMMMMMMMMMNd,:oxOOxc'..;:ll;.                                                                                                                  
                                                                                                   ..     .dNMMMMMMMMMMMMMW0o;.          ,0MMMMMMWXOdoookNMMMMMMMMMMMMMWO,    ...                                                                                                                           
                                                                                                          lNMMMMMMMMMMMMMMMMMW0dc'.      ,KMWN0kddddONMMMMMMMMMMMMMMMMMMMk.                                                                                                                                 
                                                                                                         .oNMMMMMMMMMMMMMMMMMMMMWN0xl:,...lddxdxOXWMMMMMMMMMMMMMMMMMMMMMMO'                                                                                                                                 
                                                                              ..                         .xWMMMMMMMMMMMMMMMMMMMMMMMMMMWX0OOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;                           ..                                                                                                    
                                                                              .od;.                      ,0MMMMMMMMMMMMMMX0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKWMMMMMMMMMMMMMNc                        .:dl.                                                                                                    
                                                                               .kN0l.                    .dXWMMMMMMMMMNK0:cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:kXXWMMMMMMMMMMK,                      'o0Nx.                                                                                                     
                                                                        .:ddol:;oNMWXd,                   'kWMMMMWNNWK:...kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc..,kNWXNWMMMMMX:                    ;xNMMXl;clodo;.                                                                                              
                                                                         .;dKWMWWMMMMMNk;.               ,OWMMMNk:.,:.   :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'  .;;.':kNMMMMK:                .:ONMMMMWWWMW0o;.                                                                                               
                                                                            .;xXWMMMMMMMNO:.  ',.      .lXMMMNk;        .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.        ,dXMMMNx'       .,.  .c0WMMMMMMMWKd;.                                                                                                  
                                                                               .cOWMMMMMMMWOokNWXd,.':l0WMMWO;          oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl          ,xNMMMXd;'..;xXWXkd0WMMMMMMMNOc.                                                                                                     
                                                                                 .;kNMMMMMMMMMMMMMNXNMMMMMW0:.         ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:          .dNMMMMMNKKNMMMMMMMMMMMMMNk;                                                                                                        
                                                                                   .;OWMMMWXNWMMMMMMMMMMMMMWNx.       'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,        :0NWMMMMMMMMMMMMMWXXWMMMWO;                                                                                                          
                                                                                     .lKKx:.lNMMMMMMMMMMMMMMMX;      .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO.      .xMMMMMMMMMMMMMMMM0;.ckK0c.                                                                                                           
                                                                                       ..   ;KMMMMMMMMMMMMMMMNOl;.. .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  ..;oKMMMMMMMMMMMMMMMWx.   ..                                                                                                             
                                                                                             'lkKWMMMMMMMMMMMMMMWX0kONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdk0NWMMMMMMMMMMMMMMNKxc.                                                                                                                   
                                                                                                .,cc;:oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKklcclc,.                                                                                                                      
                                                                                                        .;lx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xc,.                                                                                                                              
                                                                                                            ..;lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoc;..                                                                                                                                  
                                                                                                                :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc                                                                                                                                       
                                                                                                               ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:                                                                                                                                      
                                                                                                              :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;                                                                                                                                     
                                                                                                             cXMMMMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMNXXNMMMMMMWWMMMMMK,                                                                                                                                    
                                                                                                           .lXWXOxlcOWMWXOo;,kMWXxcoKMMWKokWMMNxco0NMKx:,lxKWMMKocdkKNW0,                                                                                                                                   
                                                                                                           .c:,.   .xOo;.   .xx:.   ,ONx. .lXXc   .;dOO:   .,lxO:   .';l;.                                                                                                                                  
                                                                                                                   ..        .       .,.    ''       ...       ..                                                                                                                                           
                                                                                                                                                                                                                                                                                                            
         
                 
                 `
export default banner;
